const currentBlock = 1;

// DOM Elements
const header = document.getElementById("header");
header.innerHTML = "Block " + currentBlock;

//example data
const data = [
  {
    success: true,
    trial_type: "fullscreen",
    trial_index: 0,
    time_elapsed: 8833,
    internal_node_id: "0.0-0.0",
  },
  {
    view_history:
      '[{"page_index":0,"viewing_time":1095.5},{"page_index":1,"viewing_time":162},{"page_index":2,"viewing_time":142.69999998807907},{"page_index":3,"viewing_time":126.30000001192093},{"page_index":4,"viewing_time":120.5},{"page_index":5,"viewing_time":141},{"page_index":6,"viewing_time":127.79999995231628}]',
    rt: 1916.3999999761581,
    disp_type: "general_instruction",
    trial_type: "instructions",
    trial_index: 1,
    time_elapsed: 10756,
    internal_node_id: "0.0-1.0",
  },
  {
    block: 0,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 2,
    time_elapsed: 12258,
    internal_node_id: "0.0-2.0-0.0",
  },
  {
    block: 0,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/ISC2/000211.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "ISC2/",
    trial_type: "html-keyboard-response",
    trial_index: 3,
    time_elapsed: 12773,
    internal_node_id: "0.0-2.0-1.0",
  },
  {
    block: 0,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 4,
    time_elapsed: 13029,
    internal_node_id: "0.0-2.0-2.0",
  },
  {
    block: 0,
    trial_num: 1,
    fix_duration: 1006.8000000119209,
    rt: 618.5,
    error: -107,
    response: 104,
    disp_type: "test-adjustment",
    route: "ISC2/",
    answer: "000211",
    trial_type: "mouse-reconstruction",
    trial_index: 5,
    time_elapsed: 14656,
    internal_node_id: "0.0-2.0-3.0",
  },
  {
    block: 0,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 6,
    time_elapsed: 16161,
    internal_node_id: "0.0-2.0-0.1",
  },
  {
    block: 0,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/ISC2/000073.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "ISC2/",
    trial_type: "html-keyboard-response",
    trial_index: 7,
    time_elapsed: 16672,
    internal_node_id: "0.0-2.0-1.1",
  },
  {
    block: 0,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 8,
    time_elapsed: 16936,
    internal_node_id: "0.0-2.0-2.1",
  },
  {
    block: 0,
    trial_num: 2,
    fix_duration: 1008.7999999523163,
    rt: 356.60000002384186,
    error: -106,
    response: 327,
    disp_type: "test-adjustment",
    route: "ISC2/",
    answer: "000073",
    trial_type: "mouse-reconstruction",
    trial_index: 9,
    time_elapsed: 18303,
    internal_node_id: "0.0-2.0-3.1",
  },
  {
    block: 0,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 10,
    time_elapsed: 19805,
    internal_node_id: "0.0-2.0-0.2",
  },
  {
    block: 0,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/ISC2/000353.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "ISC2/",
    trial_type: "html-keyboard-response",
    trial_index: 11,
    time_elapsed: 20321,
    internal_node_id: "0.0-2.0-1.2",
  },
  {
    block: 0,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 12,
    time_elapsed: 20574,
    internal_node_id: "0.0-2.0-2.2",
  },
  {
    block: 0,
    trial_num: 3,
    fix_duration: 1014.7999999523163,
    rt: 433.60000002384186,
    error: 41,
    response: 34,
    disp_type: "test-adjustment",
    route: "ISC2/",
    answer: "000353",
    trial_type: "mouse-reconstruction",
    trial_index: 13,
    time_elapsed: 22023,
    internal_node_id: "0.0-2.0-3.2",
  },
  {
    rt: 1007.3999999761581,
    stimulus:
      '<p class="unselectable" style="color: black; font-size: 20px;">Practice trials are done!</br>Click the <i>Start</i> button to start the main experiment.</br></br>The main experiment consists of 9 trials.</br>There will be a short break every 3 trials.',
    button_pressed: "0",
    disp_type: "start-mainExp",
    trial_type: "html-button-response",
    trial_index: 14,
    time_elapsed: 23032,
    internal_node_id: "0.0-3.0",
  },
  {
    block: 1,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 15,
    time_elapsed: 24522,
    internal_node_id: "0.0-4.0-0.0",
  },
  {
    block: 1,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/STB9/000014.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "STB9/",
    trial_type: "html-keyboard-response",
    trial_index: 16,
    time_elapsed: 25037,
    internal_node_id: "0.0-4.0-1.0",
  },
  {
    block: 1,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 17,
    time_elapsed: 25302,
    internal_node_id: "0.0-4.0-2.0",
  },
  {
    block: 1,
    trial_num: 1,
    fix_duration: 1008.6000000238419,
    rt: 1028.5999999642372,
    error: -30,
    response: 344,
    disp_type: "test-adjustment",
    route: "STB9/",
    answer: "000014",
    trial_type: "mouse-reconstruction",
    trial_index: 18,
    time_elapsed: 27340,
    internal_node_id: "0.0-4.0-3.0",
  },
  {
    block: 1,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 19,
    time_elapsed: 28843,
    internal_node_id: "0.0-4.0-0.1",
  },
  {
    block: 1,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/STB9/000309.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "STB9/",
    trial_type: "html-keyboard-response",
    trial_index: 20,
    time_elapsed: 29345,
    internal_node_id: "0.0-4.0-1.1",
  },
  {
    block: 1,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 21,
    time_elapsed: 29610,
    internal_node_id: "0.0-4.0-2.1",
  },
  {
    block: 1,
    trial_num: 2,
    fix_duration: 1000.5999999642372,
    rt: 296.60000002384186,
    error: -49,
    response: 260,
    disp_type: "test-adjustment",
    route: "STB9/",
    answer: "000309",
    trial_type: "mouse-reconstruction",
    trial_index: 22,
    time_elapsed: 30908,
    internal_node_id: "0.0-4.0-3.1",
  },
  {
    block: 1,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 23,
    time_elapsed: 32420,
    internal_node_id: "0.0-4.0-0.2",
  },
  {
    block: 1,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/STB9/000206.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "STB9/",
    trial_type: "html-keyboard-response",
    trial_index: 24,
    time_elapsed: 32937,
    internal_node_id: "0.0-4.0-1.2",
  },
  {
    block: 1,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 25,
    time_elapsed: 33201,
    internal_node_id: "0.0-4.0-2.2",
  },
  {
    block: 1,
    trial_num: 3,
    fix_duration: 1000.7999999523163,
    rt: 217.60000002384186,
    error: 159,
    response: 5,
    disp_type: "test-adjustment",
    route: "STB9/",
    answer: "000206",
    trial_type: "mouse-reconstruction",
    trial_index: 26,
    time_elapsed: 34420,
    internal_node_id: "0.0-4.0-3.2",
  },
  {
    rt: 52704.799999952316,
    stimulus:
      '<div class="unselectable" style="font-size:20px;">Block 1 is done!<br><br>After a 5 second break, you may press the button to proceed. Please do not take a break longer than 3 minutes.</div><div class="unselectable" style="font-size:20px;" id="clock"></div><div class="unselectable" style="font-size:20px;color:red;" id="breakPrompt"></div>',
    button_pressed: "0",
    disp_type: "prac_block_done",
    trial_type: "html-button-response",
    trial_index: 27,
    time_elapsed: 87135,
    internal_node_id: "0.0-5.0",
  },
  {
    block: 2,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 28,
    time_elapsed: 88643,
    internal_node_id: "0.0-6.0-0.0",
  },
  {
    block: 2,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/JMP3/000344.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "JMP3/",
    trial_type: "html-keyboard-response",
    trial_index: 29,
    time_elapsed: 89147,
    internal_node_id: "0.0-6.0-1.0",
  },
  {
    block: 2,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 30,
    time_elapsed: 89403,
    internal_node_id: "0.0-6.0-2.0",
  },
  {
    block: 2,
    trial_num: 1,
    fix_duration: 1012.8999999761581,
    rt: 437.2000000476837,
    error: 174,
    response: 158,
    disp_type: "test-adjustment",
    route: "JMP3/",
    answer: "000344",
    trial_type: "mouse-reconstruction",
    trial_index: 31,
    time_elapsed: 90854,
    internal_node_id: "0.0-6.0-3.0",
  },
  {
    block: 2,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 32,
    time_elapsed: 92359,
    internal_node_id: "0.0-6.0-0.1",
  },
  {
    block: 2,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/JMP3/000059.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "JMP3/",
    trial_type: "html-keyboard-response",
    trial_index: 33,
    time_elapsed: 92870,
    internal_node_id: "0.0-6.0-1.1",
  },
  {
    block: 2,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 34,
    time_elapsed: 93132,
    internal_node_id: "0.0-6.0-2.1",
  },
  {
    block: 2,
    trial_num: 2,
    fix_duration: 1014.6999999880791,
    rt: 1681.5,
    error: -46,
    response: 13,
    disp_type: "test-adjustment",
    route: "JMP3/",
    answer: "000059",
    trial_type: "mouse-reconstruction",
    trial_index: 35,
    time_elapsed: 95829,
    internal_node_id: "0.0-6.0-3.1",
  },
  {
    block: 2,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 36,
    time_elapsed: 97334,
    internal_node_id: "0.0-6.0-0.2",
  },
  {
    block: 2,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/JMP3/000230.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "JMP3/",
    trial_type: "html-keyboard-response",
    trial_index: 37,
    time_elapsed: 97839,
    internal_node_id: "0.0-6.0-1.2",
  },
  {
    block: 2,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 38,
    time_elapsed: 98091,
    internal_node_id: "0.0-6.0-2.2",
  },
  {
    block: 2,
    trial_num: 3,
    fix_duration: 1000,
    rt: 256.80000001192093,
    error: 19,
    response: 249,
    disp_type: "test-adjustment",
    route: "JMP3/",
    answer: "000230",
    trial_type: "mouse-reconstruction",
    trial_index: 39,
    time_elapsed: 99348,
    internal_node_id: "0.0-6.0-3.2",
  },
  {
    rt: 5457.600000023842,
    stimulus:
      '<div class="unselectable" style="font-size:20px;">Block 2 is done!<br><br>After a 5 second break, you may press the button to proceed. Please do not take a break longer than 3 minutes.</div><div class="unselectable" style="font-size:20px;" id="clock"></div><div class="unselectable" style="font-size:20px;color:red;" id="breakPrompt"></div>',
    button_pressed: "0",
    disp_type: "prac_block_done",
    trial_type: "html-button-response",
    trial_index: 40,
    time_elapsed: 104807,
    internal_node_id: "0.0-7.0",
  },
  {
    block: 3,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 41,
    time_elapsed: 106319,
    internal_node_id: "0.0-8.0-0.0",
  },
  {
    block: 3,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/OLM7/000289.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "OLM7/",
    trial_type: "html-keyboard-response",
    trial_index: 42,
    time_elapsed: 106827,
    internal_node_id: "0.0-8.0-1.0",
  },
  {
    block: 3,
    trial_num: 1,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 43,
    time_elapsed: 107089,
    internal_node_id: "0.0-8.0-2.0",
  },
  {
    block: 3,
    trial_num: 1,
    fix_duration: 1002.3000000119209,
    rt: 385.69999998807907,
    error: -37,
    response: 252,
    disp_type: "test-adjustment",
    route: "OLM7/",
    answer: "000289",
    trial_type: "mouse-reconstruction",
    trial_index: 44,
    time_elapsed: 108478,
    internal_node_id: "0.0-8.0-3.0",
  },
  {
    block: 3,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 45,
    time_elapsed: 109993,
    internal_node_id: "0.0-8.0-0.1",
  },
  {
    block: 3,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/OLM7/000217.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "OLM7/",
    trial_type: "html-keyboard-response",
    trial_index: 46,
    time_elapsed: 110503,
    internal_node_id: "0.0-8.0-1.1",
  },
  {
    block: 3,
    trial_num: 2,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 47,
    time_elapsed: 110766,
    internal_node_id: "0.0-8.0-2.1",
  },
  {
    block: 3,
    trial_num: 2,
    fix_duration: 1000.5,
    rt: 375.39999997615814,
    error: 142,
    response: 359,
    disp_type: "test-adjustment",
    route: "OLM7/",
    answer: "000217",
    trial_type: "mouse-reconstruction",
    trial_index: 48,
    time_elapsed: 112143,
    internal_node_id: "0.0-8.0-3.1",
  },
  {
    block: 3,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div class="unselectable" id="full_arena" style="font-size:24px;">+</div></div>',
    key_press: null,
    disp_type: "fixation",
    trial_type: "html-keyboard-response",
    trial_index: 49,
    time_elapsed: 113649,
    internal_node_id: "0.0-8.0-0.2",
  },
  {
    block: 3,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena""><img draggable="false" src="https://raw.githubusercontent.com/LWest001/DemoRouteWheel/main/OLM7/000013.jpg "></div></div>',
    key_press: null,
    disp_type: "test_target",
    route: "OLM7/",
    trial_type: "html-keyboard-response",
    trial_index: 50,
    time_elapsed: 114157,
    internal_node_id: "0.0-8.0-1.2",
  },
  {
    block: 3,
    trial_num: 3,
    rt: null,
    stimulus:
      '<div class="unselectable" id="basic_arena"><div id="full_arena" style="font-size:24px;"><img draggable="false" src="stimuli/mask.png"></img></div></div>',
    key_press: null,
    disp_type: "mask",
    trial_type: "html-keyboard-response",
    trial_index: 51,
    time_elapsed: 114421,
    internal_node_id: "0.0-8.0-2.2",
  },
  {
    block: 3,
    trial_num: 3,
    fix_duration: 1011,
    rt: 447.10000002384186,
    error: -175,
    response: 198,
    disp_type: "test-adjustment",
    route: "OLM7/",
    answer: "000013",
    trial_type: "mouse-reconstruction",
    trial_index: 52,
    time_elapsed: 115881,
    internal_node_id: "0.0-8.0-3.2",
  },
  {
    rt: 1438,
    stimulus:
      '<div class="unselectable" style="font-size:20px;">Final block is done!<br><br>Press the button to save data and move on to the end of the experiment.<br></div>',
    button_pressed: "0",
    disp_type: "prac_block_done",
    trial_type: "html-button-response",
    trial_index: 53,
    time_elapsed: 117320,
    internal_node_id: "0.0-9.0",
  },
  {
    block: 3,
    trial_num: 0,
    rt: null,
    stimulus: "<p>We are saving your data, please stay on this page.</p>",
    key_press: null,
    conf_code: 1106,
    trial_type: "html-keyboard-response",
    trial_index: 54,
    time_elapsed: 120335,
    internal_node_id: "0.0-10.0",
  },
];

// filter out trials
const trials = data.filter(
  (entry) => entry.trial_type === "mouse-reconstruction"
);

// separate by block
const responses = {};

for (let i = 0; i < total_blocks; i++) {
  responses[i] = trials.filter((trial) => trial.block === i);
}
console.log({ data, total_blocks, responses });
